name: Rebuild

on:
  push:

env:
  MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
  MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        profile: [fatjar, with-libby]
        hytale-tag: [release, pre-release]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Get latest commit hash
        run: echo "LATEST_COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Get latest version
        run: echo "VERSION=0.0.3" >> $GITHUB_ENV
      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils
      - name: Get latest hytale version for ${{ matrix.hytale-tag }}
        run: |
          HYTALE_VERSION=$(curl -fsSL https://maven.hytale.com/${{ matrix.hytale-tag }}/com/hypixel/hytale/Server/maven-metadata.xml | xmllint --xpath "string(//metadata/versioning/latest)" -)
          echo "Latest version: $HYTALE_VERSION"
          echo "HYTALE_VERSION=$HYTALE_VERSION" >> $GITHUB_ENV
      - name: Set up Java 25
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: maven
          server-id: hytalemodding.snapshots
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Build ${{ matrix.profile }} for ${{ matrix.hytale-tag }}
        run: mvn --batch-mode clean package -P ${{ matrix.profile }} -Drevision=$VERSION+$LATEST_COMMIT_HASH -Dhytale-version=$HYTALE_VERSION
      - name: Upload ${{ matrix.profile }} artifact
        uses: actions/upload-artifact@v6
        with:
          name: HyYap-${{ matrix.profile }} for ${{ matrix.hytale-tag }}
          path: ./target/${{ matrix.profile }}/HyYap-*.jar
          if-no-files-found: error
      - name: Deploy ${{ matrix.profile }} for ${{ matrix.hytale-tag }}
        if: ${{ matrix.profile == 'with-libby' }}
        run: |
          if [ "${{ matrix.hytale-tag }}" = "release" ]; then
            UPLOAD_VERSION="$VERSION-$LATEST_COMMIT_HASH+release"
          else
            UPLOAD_VERSION="$VERSION-$LATEST_COMMIT_HASH"
          fi
          mvn --batch-mode deploy -P ${{ matrix.profile }} -Drevision=$UPLOAD_VERSION -Dhytale-version=$HYTALE_VERSION -DaltReleaseDeploymentRepository=hytalemodding.snapshots::https://maven.hytalemodding.dev/snapshots
      - name: Upload to modtale
        if: ${{ matrix.hytale-tag == 'release' }}
        run: |
          if [ "${{ matrix.profile }}" = "with-libby" ]; then
            UPLOAD_VERSION="${VERSION}-${LATEST_COMMIT_HASH}"
          else
            UPLOAD_VERSION="${VERSION}-${LATEST_COMMIT_HASH}+fatjar"
          fi
          JAR_PATH=$(find target/${{ matrix.profile }} -type f -name 'HyYap-*.jar' | head -n 1)
          
          echo "Found Jar: $JAR_PATH"
          echo "Publishing Version: $UPLOAD_VERSION"

          curl --fail-with-body -X POST "https://api.modtale.net/api/v1/projects/${{ vars.PROJECT_ID }}/versions" \
            -H "X-MODTALE-KEY: ${{ secrets.MODTALE_TOKEN }}" \
            -F "file=@$JAR_PATH" \
            -F "versionNumber=$UPLOAD_VERSION" \
            -F "gameVersions=$HYTALE_VERSION" \
            -F "channel=BETA" \
            -F "changelog=Automated Build & Release from GitHub"
